language: objective-c
osx_image: xcode7.2

install: true
before_script: travis/before_script.sh
script: travis/script.sh

notifications:
  slack:
    secure: NnQtag2t7iuRKIwTRMoUX4d95dOr76qfqRG0j0PjhHGViF/wjEgYF4lxnpEcHFOuwjgsoPtwGlWbwR7idIU+Zp/JmUWZRfUgWE3zzt9rhRe84yII9N8n2/tvylwgEYldEG2+VUM4Mo5YBj9IyQkW6DBzXkOkOU0Nnzzqw7irN8uOV6+iso33wz6YgJP+ykxqflsPTchgYlOA90Eb4O3dt4ySKCspPQfDmKj8AdiQeVJQrt+aN3lu68xzhjLrsiGc6bRLT0OCceSA4j6ak5vzaRgcKPFHPZgC2zeQk6IzSXO63xA9RzXUKwCeuRg34WtYR8RLJWNsgKO3CAqpM/YlNeYhkV8B3EECFzuwSgSPdzszRrF9cZx2lGsIg64Ljk48cHfE4agv3/m6/auIA9So1SclMwvgL2t88SN/UUkffP0KDNm6svNNblTvAA/2lgf46a8rYGMxKOws4F4J7SMb6ZVyTTxONNcJUx/Zjw5I+M3HxB2Z7Pl1W7hwlGAq0EGs7U7u3U6vK5LL90fM9yzqFqtnrbg6DyzA0hpn64BjooZFAEh8DIOPONJFfGpDvkAbIQ57VDveVGkQNtKGWv/UA8iIWrgDfOTFDEwnO0zXoVE2nPcxoFNvlpiazPSypksJJi7CO5PQEdSH64NPmEoGBSFHDvGCQRjHR4GBn33tlF8=
